### ISSUE TITLE
Input isn't populated on reload

### ISSUE THREAD

**Issue by oskarrough** [danskdynamit/discourse-links-category#1]
To reproduce:
1. Edit an already existing topic using the featured link field
2. With the editor open, reload the page
3. The editor will open automatically on reload but the link field isn't filled any longer

If you tap 'Edit' again, it'll fill correctly.

**Comment by erickguan** [comment]
Fixed per f268a56f511aeaf6bb5ceddd25462dd47ea5d348

**Comment by oskarrough** [comment]
Thank you, again!

**Comment by erickguan** [comment]
You are welcome :) How is the plugin working as you expect? Even with more edge cases, like move in/out?

**Comment by Battin** [comment]
Works perfectly!
