### ISSUE TITLE
Could not find module `discourse/views/header`

### ISSUE THREAD

**Issue by oskarrough** [danskdynamit/discourse-links-category#2]
Getting the following error after updating the plugin as of today together with Discourse 2.6.0 beta2.

```
_vendor-bc7ecd0….js:1599Uncaught Error: Could not find module `discourse/views/header` imported from `discourse/plugins/discourse-links-category/discourse/initializers/discourse-links-category`
```

**Comment by erickguan** [comment]
Do you update to the `tests-passed` branch?

Anyway, I will look into the new update to the core. It's a performance boost:
https://meta.discourse.org/t/help-us-test-the-new-header-code/43184

**Comment by erickguan** [comment]
I fixed the loading problem. I'll fix displaying links on the title once the API is ready.

**Comment by oskarrough** [comment]
Which `tests-passed` branch?

Just rebuilt our Discourse instance to get your last fix and it works — thank you!

**Comment by erickguan** [comment]
Never mind. I am talking about header rewrite in the core

But I got some regression due to core update. I'll keep this issue open for some days as a record

**Comment by erickguan** [comment]
All fixed
