### ISSUE TITLE
Broken in Safari 8

### ISSUE THREAD

**Issue by oskarrough** [danskdynamit/discourse-links-category#3]
hi, not quite sure what this bug is but when I visit our Discourse site with this plugin enabled with Safari 8 (os x yosemite) I get the following error message and application doesn't boot.

`undefined is not a function (evaluating 'e.startsWith("www")')`

![screen shot 2016-08-02 at 23 13 38](https://cloud.githubusercontent.com/assets/184567/17345529/c9e9d8d6-5906-11e6-8ed7-0bc9150ec83d.png)

I couldn't properly trace it down, seemed buried in an Ember stack trace I checked via saucelabs. Perhaps it's here https://github.com/danskdynamit/discourse-links-category/blob/ce0d1875edb55088010e18ebb0ee6cd2d59ab9ff/assets/javascripts/discourse/widgets/featured-link.js.es6#L6-L28

If I disable the "links category enabled" setting the site works again. Any ideas?

**Comment by erickguan** [comment]
Old safari doesn't support a function call. I found another spot on core is using this function. I will report to the team and see what I can do to this.
