### ISSUE TITLE
Avoid extra click handler

### ISSUE THREAD

**Issue by oskarrough** [danskdynamit/discourse-links-category#5]
Can we refactor the featured-link to get rid of the click handler in order not to overwrite any default browser behaviour, like ctrl+click to open in a new tab.

https://github.com/danskdynamit/discourse-links-category/blob/master/assets/javascripts/discourse/widgets/featured-link.js.es6#L36-L49

Could we change this to something like a computed property that returns `target="_blank"` or `target="_self"` (or nothing at all) depending on `this.siteSettings.links_category_open_in_external_tab`? Or something better?

**Comment by erickguan** [comment]
I'll look into that.

**Comment by erickguan** [comment]
Fixed in the 1.7 :)

**Comment by oskarrough** [comment]
Hey, thanks so much. I've updated the plugin to 1.7 and it works.
